### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by streaps** [Haxe18/telekom_fon_connect#1]
It is not working with Python 3.6.8 on Ubuntu 18.10

```
$ ./telekom_fon_connect.py -c telekom_fon_connect.conf 
2019-05-17 12:02:31,793 INFO log_level is : DEBUG
Traceback (most recent call last):
  File "./telekom_fon_connect.py", line 331, in <module>
    sys.exit(main())                                                                  # If no arg, pass none
  File "./telekom_fon_connect.py", line 302, in main
    online_request = do_request(url=test_url, do_head_only=True, want_header='location',level=loglvl)  # Do head reguest to check online status
  File "./telekom_fon_connect.py", line 102, in do_request
    reset_http_debug_out(http_log)                                               # Call final part of HTTP Debug output
  File "./telekom_fon_connect.py", line 54, in reset_http_debug_out
    debug_info = ''.join(http_log.content).replace('\\r', '').decode('string_escape').replace('\'', '')
AttributeError: 'str' object has no attribute 'decode'

```

**Comment by Haxe18** [comment]
Hi mate,

can confirm and fix the problem.
The error seems to be common with python3 and i am wondering why i don't got the error on testing with python3 myself.

Unfortunately github sends me no information about you issue but i saw it myself these days :)
